import cadiz from "../../img/teams/cadiz.png";
import getafe from "../../img/teams/getafe.png";
import cvf from "../../img/teams/cvf.png";
import fcb from "../../img/teams/fcb.png";
import deportivo from "../../img/teams/deportivo.png";
import elche from "../../img/teams/elche.png";
import RMa from "../../img/teams/rfc.png";
import rccelta from "../../img/teams/rccelta.png";
import espanyol from "../../img/teams/espanyol.png";
import rayo from "../../img/teams/rayo.png";
import atletico from "../../img/teams/atletico.png";
import athletic from "../../img/teams/athletic.png";
import mallorca from "../../img/teams/mallorca.png";
import granada from "../../img/teams/granada.png";
import osasuna from "../../img/teams/osasuna.png";
import rsoc from "../../img/teams/rsoc.png";
import rbf from "../../img/teams/rbf.png";
import sevilla from "../../img/teams/sevilla.png";
import levante from "../../img/teams/levante.png";
import valencia from "../../img/teams/valencia.png";

export const tableteam = [
  {
    id: 1,
    teampng: RMa,
    teamname: "Real Madrid",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 2,
    teampng: fcb,
    teamname: "Barcelona",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 3,
    teampng: atletico,
    teamname: "Atletico Madrid",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 4,
    teampng: rbf,
    teamname: "Real Betis",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 5,
    teampng: cvf,
    teamname: "Villareal",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 6,
    teampng: sevilla,
    teamname: "Sevilla FC",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 7,
    teampng: levante,
    teamname: "Levante UD",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 8,
    teampng: valencia,
    teamname: "Real Betis",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 9,
    teampng: granada,
    teamname: "Granada CF",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 10,
    teampng: athletic,
    teamname: "ATHLETIC CLUB",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 11,
    teampng: rccelta,
    teamname: "RC CELTA",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 12,
    teampng: espanyol,
    teamname: "RCD ESPANYOL",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 13,
    teampng: rayo,
    teamname: "RAYO VALLECANO",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 14,
    teampng: rsoc,
    teamname: "REAL SOCIEDAD",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 15,
    teampng: elche,
    teamname: "ELCHE CF",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 16,
    teampng: osasuna,
    teamname: "CA OSASUNA",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 17,
    teampng: mallorca,
    teamname: "RCD MALLORCA",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 18,
    teampng: cadiz,
    teamname: "CÁDIZ CF",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 19,
    teampng: getafe,
    teamname: "GETAFE CF",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
  {
    id: 20,
    teampng: deportivo,
    teamname: "DEPORTIVO ALAVÉS",
    goalscored: 80,
    goalcon: 31,
    shots: 256,
    fouls: 394,
    yellow: 36,
    red: 0,
  },
];
